"""
Delete Some Assignments 

Takes a csv of assignment ids to delete. Like the one generated by
make_multiple_assignments_with_grades, if for example, you make the
assignments wrong...

Requires: CSV of assignments. Columns 'Assignment ID' and 'Section ID'
are required

Usage: ./delete_some_assignments {schoolcode} {filename}

Returns: Nothing but a confirmation message

"""


import sys
import qs


def main():
    qs.logger.config(__file__)
    
    schoolcode = sys.argv[1]
    filename = sys.argv[2]
    q = qs.API(schoolcode)
    csv_assignments = qs.CSV(filename)

    # Check for missing columns

    missing_columns = []
    if 'Section ID' not in csv_assignments.cols:
        missing_columns.append('Section ID')
    if 'Assignment ID' not in csv_assignments.cols:
        missing_columns.append('Assignment ID')

    if missing_columns:
        for missing_column in missing_columns:
            qs.logger.info('Missing columns: ', missing_columns, cc_print=True)
            sys.tracebacklimit = 0
            raise ValueError("Columns Missing. See above for details.")

    # Delete Assignments
     
    for assign in qs.bar(csv_assignments):
        assignment = assign['Assignment ID']
        section = assign['Section ID']

        q.delete_assignment(section, assignment)

    qs.logger.info('Assignments deleted', cc_print=True)


if __name__ == '__main__':
    main()
